# vim: set filetype=tcl :

# test for example/inflate

proc test_inflate {test_name src_str level} {
    global exampledir

    set tempfile [file tempfile tempfilename]
    try {
        # deflate(compress) src_str and write the result in the tempfile
        fconfigure $tempfile -encoding binary
        puts -nonewline $tempfile [zlib deflate $src_str $level]
        close $tempfile
    
        set inflated [exec $exampledir/inflate $tempfilename]
        if {$inflated == $src_str} {
            pass "$test_name passed.\n"
        } else {
            fail "$test_name failed: expected \"$src_str\".\n"
        }
    } finally {
        file delete $tempfilename
    }
}

test_inflate "Stored" "hello" 0
test_inflate "Stored 255 bytes" [string repeat x 255] 0
test_inflate "Stored 256 bytes" [string repeat x 256] 0
test_inflate "Stored 65535 bytes" [string repeat x 65535] 0
test_inflate "Stored 65536 bytes" [string repeat x 65536] 0
